apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-app
  namespace: argocd
spec:
  project: postgresql-project
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.2.6  # lub latest
    helm:
      releaseName: postgresql
      valueFiles:
        - $values/values-pg.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'git@github.com:sieczak-a/helm-argo.git'
      targetRevision: HEAD  # lub konkretny branch/tag/commit
      ref: values
